### ISSUE TITLE
Ribbon cable source

### ISSUE THREAD

**Issue by tvigers** [gilbertfrancois/enviro-plus-case#1]
Hi,

Was just wondering where you were able to source a ribbon cable like that?

I've searched around a little bit but have been unable to find one that short/have a perfect angle like that?

Cheers,

Tim

**Comment by gilbertfrancois** [comment]
I modified the cable myself. It is a standard male to female 40pins IDE harddisk ribbon cable. I carefully opened the grey male plug and placed it at the desired position. Then I've cut the ribbon cable to its new length.
